apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-a
  name: deployment-a
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-a
    spec:
      containers:
      - image: dejanualex/app_a:1.0
        name: app-a-st2qz
        ports:
        - containerPort: 5000
        resources: {}
status: {}
