apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-b
  name: svc-b
  namespace: default
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: app-b
status:
  loadBalancer: {}
