apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-a
  name: svc-a
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: deployment-a
status:
  loadBalancer: {}
